<HTML>
<HEAD>
<TITLE>Electronic Conference on Foundations of Information Science</TITLE>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<META NAME="KEYWORDS" CONTENT="Electronic Conference;Information Science;MDPI" />
<META NAME="DESCRIPTION" CONTENT="Electronic Conference on THE NATURE OF INFORMATION: CONCEPTIONS, MISCONCEPTIONS, AND PARADOXES,6-10 May 2002" />
<script type="text/javascript" language="javascript1.2">
 if(navigator.appName.indexOf("Netscape") >0) {
        document.writeln('<link rel="stylesheet" href="inc/nc.css" type ="text/css">');}
 else{
        document.writeln('<link rel="stylesheet" href="inc/ie.css" type ="text/css">');}
</script>
</HEAD>
<BODY BGCOLOR=#FFFFFF leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<TABLE WIDTH=778 BORDER=0 CELLPADDING=0 CELLSPACING=0>
	<TR>
		<TD COLSPAN=5>
			<IMG SRC="images/top_01.gif" WIDTH=778 HEIGHT=3></TD>
	</TR>
	<TR>
		<TD>
			<IMG SRC="images/top_02.gif" WIDTH=7 HEIGHT=72></TD>
		<TD>
			<IMG SRC="images/top_03.gif" WIDTH=334 HEIGHT=72></TD>
		<TD>
			<a href="../../fis.iguw.tuwien.ac.at/default.htm" target="_blank"><IMG SRC="images/top_04.gif" WIDTH=136 HEIGHT=72 border=0 ALT="Foundations of Information Science"></a></TD>
		<TD>
			<IMG SRC="images/top_05.gif" WIDTH=289 HEIGHT=72></TD>
		<TD>
			<IMG SRC="images/top_06.gif" WIDTH=12 HEIGHT=72></TD>
	</TR>
	<TR>
		<TD COLSPAN=5>
			<IMG SRC="images/top_07.gif" WIDTH=778 HEIGHT=7></TD>
	</TR>
</TABLE><table width="778" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td height="15" width="13" background="images/bg.gif">&nbsp;</td>
    <td height="15" width="158" background="images/bg.gif">&nbsp;</td>
    <td height="15" width="39">&nbsp;</td>
    <td height="15" width="489">&nbsp;</td>
    <td height="15" width="10">&nbsp;</td>
    <td height="15" width="69">&nbsp;</td>
  </tr>
  <tr>
    <td width="13" background="images/bg.gif">&nbsp;</td>
    <td width="158" background="images/bg.gif" valign="top"> <table width="153" border="0" cellspacing="0" cellpadding="0" height="259">
        <tr> 
          <td background="images/gray.gif" height="182" align="left" valign="top"> 
            <table width="151" border="0" cellspacing="1" cellpadding="1" background="images/blank.gif" height="212">
              <tr> 
                <td align="center" valign="middle" bgcolor="#ffcc99" height="22"><a href="index.php" target="_top">Home</a></td>
              </tr>
              <tr> 
                <td align="center" valign="middle" height="22"><a href="index.php@action=topics" target="_top">Topics</a></td>
              </tr>
              <tr> 
                <td align="center" valign="middle" height="22"><a href="index.php@action=contacts" target="_top">Contacts</a></td>
              </tr>
              <tr> 
                <td align="center" valign="middle" height="22"><a href="index.php@action=sch" target="_top">Schedule</a></td>
              </tr>
              <tr> 
                <td align="center" valign="middle" height="22"><a href="index.php@action=reg" target="_top">Registration 
                  </a></td>
              </tr>
              <tr> 
                <td align="center" valign="middle" height="34"><a href="index.php@action=advisory" target="_top">Advisory Board</a> </td>
              </tr>
              <tr> 
                <td align="center" valign="middle" height="34"><a href="index.php@action=abstract" target="_top">Abstract and Paper Submission </a></td>
              </tr>
              <tr> 
                <td align="center" valign="middle" height="34"><a href="index.php@action=pub" target="_top">Presentation and Publication</a> </td>
              </tr>
              <tr>
                <td align="center" valign="middle" height="34"><a href="index.php@action=corp" target="_top">Corporate Sponsorship Opportunities</a></td>
              </tr>
            </table>
          </td>
        </tr>
      </table></td>
    <td width="39">&nbsp;</td>
    <td width="489" valign="top" class="main">
        <p align="right"><img alt="Print This Page" hspace="0" src="images/print.gif" border="0" width="18" height="13"><a title="Use the 'Print This Page' service to get the text on this page in easier format for printing." href="print.php@action=index" target="_blank">Print This Page</a></p>
              <center>

        <p><b><font color="#000099">Electronic Conference on Foundations of Information Science
</font></b> 

          <br>

          <b><font color="#000066"><i>THE NATURE OF INFORMATION: CONCEPTIONS, MISCONCEPTIONS, AND PARADOXES
</i><br>

         </font></b> <br>
    <b><font color="#990000">(FIS2002, www.mdpi.net/fis2002/) </font></b> <br>
    <b>6-10 May 2002</b> 
</center>

      
<p>The Electronic Conference on Foundations of Information Science THE NATURE OF INFORMATION: CONCEPTIONS, MISCONCEPTIONS, AND PARADOXES will be held on the Internet from <b>6-10 May 2002</b> 
  and will be served through the conference Web site location: <a href="default.htm">http://www.mdpi.net/fis2002/</a>. 
  On behalf of the organisers we invite you to attend this Symposium which is 
  free to present and participate in. Please register for the conference through 
  this Web site to obtain access for the conference and to remain informed on 
  the conference program and news. 

<p>The conference will consist of invited and contributed electronic posters and 
  slideshows presented through the conference Web site and Web-based discussions 
  of the topics and presentations during the conference. Subsequent to the conference 
  an electronic proceedings will be made available on both CD and the Internet. 
  Selected papers will be invited for peer-reviewed publication in the MDPI electronic 
  journal <i>Entropy</i>, www.mdpi.org/entropy/.<br>
</p>
<p><b>Koichiro Matsuno<br>
  Peter Erdi<br>
  John Collier</b><br>
  <i>Conference Chairs</i> 
<p><b><a href="mailto:marijuan@posta.unizar.es">Pedro C. Marijuan</a> (organizer) </b><br>
 
<b><a href="../../info.tuwien.ac.at/histu/pers/12661.html" target="_blank">Wolfgang 
  Hofkirchner</a> </b><br>
  <i>Scientific Secretariat</i> </p>

      
<p><b>Dr. Shu-Kun Lin</b><br>
  <i>Technical Secretariat </i>
        <p>&nbsp;</p>
        </td>
    <td width="10">&nbsp;</td>
    <td width="69">&nbsp;</td>
  </tr>
  <tr>
    <td height="5" width="13" background="images/bg.gif">&nbsp;</td>
    <td height="5" width="158" background="images/bg.gif">&nbsp;</td>
    <td height="5" width="39">&nbsp;</td>
    <td height="5" width="489">&nbsp;</td>
    <td height="5" width="10">&nbsp;</td>
    <td height="5" width="69">&nbsp;</td>
  </tr>
</table>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr> 
    <td bgcolor="#e8e8e8" height="34" valign="bottom" class="copyright"> 
      <p align="center">Webmaster: <a href="mailto:ec@mdpi.org?subject=Re:FIS2002">John Yuan</a>&nbsp; Web design: Xiao Xin<i>&nbsp;&nbsp;Last 
        change: 19 December 2001</i><br>
        &copy; 2001 MDPI, Saengergasse 25, CH-4054 Basel, Switzerland</p>
    </td>
  </tr>
</table></BODY>
</HTML>